export enum ConstantsEnum {
  ROLES = 'roles',
  BEARER = 'Bearer',
  FEED = 'feed',
  ACCESS_TOKEN = 'access_token=',
  COMMENTS = 'comments',
  SUBSCRIBE = 'subscribe',
  OFFSET = 'offset',
  LIMIT = 'limit',
  FIELDS = 'fields',
  FULL_PICTURE = 'full_picture',
  MESSAGE = 'message',
  ID = 'id',
  SUPPORT = 'Support',
  SUPPORT_TEMPLATE = 'support',
  NAME = 'name',
  EMAIL = 'email',
  PHONE = 'phone',
  PRICE = 'price',
  INDEX = 'index',
  DUE_DATE = 'dueDate',
  S3 = 'S3',
  RESPONSIBLE = 'responsible',
  CREATED = 'createdAt',
}
